env:
  browser: true
  es2022: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:solid/typescript'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 'latest'
  ecmaFeatures:
    - jsx: true
plugins:
  - '@typescript-eslint'
  - 'solid'
rules: {}
